"""Add prompts table for prompt management

Revision ID: 014b7e4874db
Revises: 4da19e3fd15b
Create Date: 2025-11-08 09:04:06.586322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '014b7e4874db'
down_revision: Union[str, None] = '4da19e3fd15b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'prompts',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('category', sa.String(length=100), nullable=False, comment='Category name (e.g., DESIGN, FUNCTIONALITY)'),
        sa.Column('subcategory', sa.String(length=100), nullable=True, comment='Subcategory name (e.g., DESIGN_SRP, FUNCTIONALITY_BUGS)'),
        sa.Column('name', sa.String(length=200), nullable=False, comment='Display name'),
        sa.Column('description', sa.Text(), nullable=True, comment='Description of what this prompt checks'),
        sa.Column('content', sa.Text(), nullable=False, comment='The actual prompt text'),
        sa.Column('system_prompt_template', sa.Text(), nullable=True, comment='Optional custom system prompt template'),
        sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this prompt is active'),
        sa.Column('is_system', sa.Boolean(), nullable=False, comment='Whether this is a system prompt (cannot be deleted)'),
        sa.Column('order_index', sa.Integer(), nullable=False, comment='Display order'),
        sa.Column('subcategory_mapping', sa.JSON(), nullable=True, comment='Mapping to subcategories'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=True, comment='User ID who created this prompt'),
        sa.Column('updated_by', sa.Integer(), nullable=True, comment='User ID who last updated this prompt'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompts_id'), 'prompts', ['id'], unique=False)
    op.create_index(op.f('ix_prompts_category'), 'prompts', ['category'], unique=False)
    op.create_index(op.f('ix_prompts_subcategory'), 'prompts', ['subcategory'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompts_subcategory'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_category'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_id'), table_name='prompts')
    op.drop_table('prompts')
    # ### end Alembic commands ###
