"""Initial migration

Revision ID: a51c4abdc400
Revises: 
Create Date: 2025-11-01 21:53:26.371881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a51c4abdc400'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('force_password_change', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Enum('GITHUB', 'GITLAB', 'ZIP', 'LOCAL', name='projectsource'), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('repository_name', sa.String(length=255), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('total_lines', sa.Integer(), nullable=False),
    sa.Column('primary_language', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'DELETED', name='projectstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_projects_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_table('audit_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='taskpriority'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.String(length=255), nullable=True),
    sa.Column('agents_used', sa.JSON(), nullable=True),
    sa.Column('scan_config', sa.JSON(), nullable=True),
    sa.Column('total_issues', sa.Integer(), nullable=False),
    sa.Column('critical_issues', sa.Integer(), nullable=False),
    sa.Column('high_issues', sa.Integer(), nullable=False),
    sa.Column('medium_issues', sa.Integer(), nullable=False),
    sa.Column('low_issues', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_audit_tasks_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_audit_tasks_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_tasks'))
    )
    op.create_index(op.f('ix_audit_tasks_created_by'), 'audit_tasks', ['created_by'], unique=False)
    op.create_index(op.f('ix_audit_tasks_id'), 'audit_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_audit_tasks_project_id'), 'audit_tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_audit_tasks_status'), 'audit_tasks', ['status'], unique=False)
    op.create_table('audit_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='issueseverity'), nullable=False),
    sa.Column('category', sa.Enum('SECURITY', 'QUALITY', 'PERFORMANCE', 'MAINTAINABILITY', 'STYLE', 'DOCUMENTATION', 'OTHER', name='issuecategory'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'IGNORED', 'FALSE_POSITIVE', name='issuestatus'), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('line_end', sa.Integer(), nullable=True),
    sa.Column('column_start', sa.Integer(), nullable=True),
    sa.Column('column_end', sa.Integer(), nullable=True),
    sa.Column('code_snippet', sa.Text(), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('fix_example', sa.Text(), nullable=True),
    sa.Column('issue_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['audit_tasks.id'], name=op.f('fk_audit_issues_task_id_audit_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_issues'))
    )
    op.create_index(op.f('ix_audit_issues_category'), 'audit_issues', ['category'], unique=False)
    op.create_index(op.f('ix_audit_issues_file_path'), 'audit_issues', ['file_path'], unique=False)
    op.create_index(op.f('ix_audit_issues_id'), 'audit_issues', ['id'], unique=False)
    op.create_index(op.f('ix_audit_issues_rule_id'), 'audit_issues', ['rule_id'], unique=False)
    op.create_index(op.f('ix_audit_issues_severity'), 'audit_issues', ['severity'], unique=False)
    op.create_index(op.f('ix_audit_issues_status'), 'audit_issues', ['status'], unique=False)
    op.create_index(op.f('ix_audit_issues_task_id'), 'audit_issues', ['task_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('download_url', sa.String(length=500), nullable=True),
    sa.Column('include_code_snippets', sa.Boolean(), nullable=True),
    sa.Column('include_suggestions', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_reports_created_by_users')),
    sa.ForeignKeyConstraint(['task_id'], ['audit_tasks.id'], name=op.f('fk_reports_task_id_audit_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_task_id'), 'reports', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_task_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_audit_issues_task_id'), table_name='audit_issues')
    op.drop_index(op.f('ix_audit_issues_status'), table_name='audit_issues')
    op.drop_index(op.f('ix_audit_issues_severity'), table_name='audit_issues')
    op.drop_index(op.f('ix_audit_issues_rule_id'), table_name='audit_issues')
    op.drop_index(op.f('ix_audit_issues_id'), table_name='audit_issues')
    op.drop_index(op.f('ix_audit_issues_file_path'), table_name='audit_issues')
    op.drop_index(op.f('ix_audit_issues_category'), table_name='audit_issues')
    op.drop_table('audit_issues')
    op.drop_index(op.f('ix_audit_tasks_status'), table_name='audit_tasks')
    op.drop_index(op.f('ix_audit_tasks_project_id'), table_name='audit_tasks')
    op.drop_index(op.f('ix_audit_tasks_id'), table_name='audit_tasks')
    op.drop_index(op.f('ix_audit_tasks_created_by'), table_name='audit_tasks')
    op.drop_table('audit_tasks')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
